export const Stories = [
  {
    attribution: null,
    tags: [],
    type: 'image',
    location: null,
    filter: 'normal',
    created_time: '53 MINUTES AGO',
    link: '',
    images: {
      low_resolution: {
        url: '',
        width: 320,
        height: 320,
      },
      thumbnail: {
        url: '',
        width: 150,
        height: 150,
      },
      standard_resolution: {
        url: '#4287f5',
        width: 640,
        height: 640,
      },
    },
    users_in_photo: [],
    caption: {
      created_time: '53 MINUTES AGO',
      text: 'Logon this is the logo of PRDP, matlab Prem Ratan Dhan Payo. Coming this Diwali',
      from: {
        username: 'beingsalmankhan',
        profile_picture: '',
        id: '14434342112',
        full_name: 'Salman Khan',
      },
      id: '2343243243232',
    },
    user_has_liked: true,
    user_has_saved: false,
    id: '13433443443_2133435435434',
    user: {
      username: 'beingsalmankhan',
      profile_picture: '#771796',
      id: '14434342112',
      full_name: 'Salman Khan',
    },
    comments: [
      {
        user: {
          username: '_s_i_a_m_',
          profile_picture: '#771796',
          id: '14434342112',
          full_name: 'HOSSAIN MAHMUD SIAM',
        },
        text: 'That legendary tour moment?😮',
      },
      {
        user: {
          username: 'mahirahkhan',
          profile_picture: '#771796',
          id: '14434342112',
          full_name: 'Mahira Khan',
        },
        text: 'eita kon jaiga?',
      },
    ],
    likedByMain: 'mahirakhan',
  },
  {
    attribution: null,
    tags: [],
    type: 'image',
    location: null,
    filter: 'normal',
    created_time: '15 HOURS AGO',
    link: '',
    images: {
      low_resolution: {
        url: '',
        width: 320,
        height: 320,
      },
      thumbnail: {
        url: '',
        width: 150,
        height: 150,
      },
      standard_resolution: {
        url: '#33ff57',
        width: 640,
        height: 640,
      },
    },
    users_in_photo: [],
    caption: {
      created_time: '15 HOURS AGO',
      text: 'Thank u all for celebrating my 30 yrs with cakes & edits and all things nice. For me the best way to celebrate is to work round the clock today to create more entertainment. Love you all.',
      from: {
        username: 'beingsalmankhan',
        profile_picture: '',
        id: '14434342112',
        full_name: 'Salman Khan',
      },
      id: '2343243243232',
    },
    user_has_liked: false,
    user_has_saved: true,
    id: '13433443443_2133432434',
    user: {
      username: 'iamsrk',
      profile_picture: '#ff5733',
      id: '14434334012',
      full_name: 'Shah Rukh Khan',
    },
    comments: [],
    likedByMain: 'sajalaly',
  },
  {
    attribution: null,
    tags: [],
    type: 'image',
    location: null,
    filter: 'normal',
    created_time: '1 DAY AGO',
    link: '',
    images: {
      low_resolution: {
        url: '',
        width: 320,
        height: 320,
      },
      thumbnail: {
        url: '',
        width: 150,
        height: 150,
      },
      standard_resolution: {
        url: '#ff33ab',
        width: 640,
        height: 640,
      },
    },
    users_in_photo: [],
    caption: {
      created_time: '1 DAY AGO',
      text: 'Jo hoshiyaari se khele usse jeet ka rasta mil hi jata hai. 😎',
      from: {
        username: 'beingsalmankhan',
        profile_picture: '',
        id: '14434342112',
        full_name: 'Salman Khan',
      },
      id: '2343243243232',
    },
    user_has_liked: false,
    user_has_saved: false,
    id: '134334325443_2133432434',
    user: {
      username: 'hrithikroshan',
      profile_picture: '#33ff57',
      id: '14434342000',
      full_name: 'Hrithik Roshan',
    },
    comments: [],
    likedByMain: 'aliaabhatt',
  },
];
